// Growth Articles feature — seed data for the `articles` table.
// Parsed directly from the user-supplied list. Deduplicated: 5 articles were
// listed under more than one growth path — those are represented once here
// with multiple entries in `growth_paths`, rather than as duplicate rows.
// 43 original list entries -> 38 unique articles.
//
// FIXED: 4 Desiring God URLs 404'd (the original slugs included a subtitle
// suffix DG has since dropped) — corrected via their site search to the
// current canonical slugs: "ask-whatever-i-wish", "spiritual-maturity-keeps-maturing",
// "the-quiet-strength-of-godly-fear", "how-healthy-is-your-soul".

export default [
  // ─── Spiritual Growth (SP) ───────────────────────────────────────────
  { title: "When Life Gets Busy, Keep Abiding", url: "https://www.desiringgod.org/articles/when-life-gets-busy-keep-abiding", cover_image_url: "https://dg.imgix.net/when-life-gets-busy-keep-abiding-aopupe4d-en/landscape/when-life-gets-busy-keep-abiding-aopupe4d-75a25c90fe968735e36aace593c98b72.jpg?ts=1782741395&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 1 },
  { title: "“I Don’t Have Time to Read Scripture” — Bad Reasons We Neglect the Bible", url: "https://www.desiringgod.org/articles/i-dont-have-time-to-read-scripture", cover_image_url: "https://dg.imgix.net/i-don-t-have-time-to-read-scripture-a4ltp87z-en/landscape/i-don-t-have-time-to-read-scripture-a4ltp87z-3238bc407de71fa749f999fa31fa7272.png?ts=1783007424&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 2 },
  { title: "“I’m Too Distracted When I Read” — Bad Reasons We Neglect the Bible", url: "https://www.desiringgod.org/articles/im-too-distracted-when-i-read", cover_image_url: "https://dg.imgix.net/i-m-too-distracted-when-i-read-3u49fxvq-en/landscape/i-m-too-distracted-when-i-read-3u49fxvq-c26b694f66b9c2cb37cb6224211627a9.png?ts=1783007208&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 3 },
  { title: "The Real Reasons We Don’t Read the Bible", url: "https://www.desiringgod.org/articles/the-real-reasons-we-dont-read-the-bible", cover_image_url: "https://dg.imgix.net/the-real-reasons-we-don-t-read-the-bible-lnj02oz2-en/landscape/the-real-reasons-we-don-t-read-the-bible-lnj02oz2-e4de7ac4b7d67f661bcd621aaad20b70.png?ts=1783007736&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 4 },
  { title: "Ask Whatever I Wish? God’s Unblushing Promises for Prayer", url: "https://www.desiringgod.org/articles/ask-whatever-i-wish", cover_image_url: "https://dg.imgix.net/ask-whatever-i-wish-6vrtscaq-en/landscape/ask-whatever-i-wish-6vrtscaq-029b0d9a7a3da8e47fc4721d7d8aeb22.jpeg?ts=1778867117&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 5 },
  { title: "Spiritual Maturity Keeps Maturing: Seven Marks of Growing Disciples", url: "https://www.desiringgod.org/articles/spiritual-maturity-keeps-maturing", cover_image_url: "https://dg.imgix.net/spiritual-maturity-keeps-maturing-s0fex8gm-en/landscape/spiritual-maturity-keeps-maturing-s0fex8gm-5f38886636f30c5fe62970e482ca9dc1.jpeg?ts=1779986440&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 6 },
  { title: "Keep Praying for a Breakthrough", url: "https://www.desiringgod.org/articles/keep-praying-for-a-breakthrough", cover_image_url: "https://dg.imgix.net/keep-praying-for-a-breakthrough-wtkgb4sa-en/landscape/keep-praying-for-a-breakthrough-wtkgb4sa-85b76bd24a4f8c454d4e46bc014f9057.jpeg?ts=1777040959&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP"], sequence_order: 7 },
  { title: "Every Woman Needs Another: A Call to Spiritual Motherhood", url: "https://www.desiringgod.org/articles/every-woman-needs-another", cover_image_url: "https://dg.imgix.net/every-woman-needs-another-2cyivsx0-en/landscape/every-woman-needs-another-2cyivsx0-d45563cfa81ed4edb4ff8c246a2d2b3c.jpg?ts=1600385717&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP", "LR"], sequence_order: 8 },
  { title: "Fearless Women in a World of Opportunities", url: "https://www.desiringgod.org/articles/fearless-women-in-a-world-of-opportunities", cover_image_url: "https://dg.imgix.net/fearless-women-in-a-world-of-opportunities-uh0evqsn-en/landscape/fearless-women-in-a-world-of-opportunities-uh0evqsn-9db6861d63ff5f5da3f52b34cb0f280a.jpg?ts=1529420971&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["SP", "PP"], sequence_order: 9 },
  // NOTE: this page's og:image is Desiring God's generic sitewide share
  // logo, not a real per-article photo — left blank so the UI falls back
  // to the title placeholder instead of showing a misleading site logo.
  { title: "A Challenge to Women", url: "https://www.desiringgod.org/articles/a-challenge-to-women", cover_image_url: "", source: "Desiring God", growth_paths: ["SP"], sequence_order: 10 },

  // ─── Life & Relationships (LR) ───────────────────────────────────────
  { title: "Romance Is Worth the Risk", url: "https://www.desiringgod.org/articles/romance-is-worth-the-risk", cover_image_url: "https://dg.imgix.net/romance-is-worth-the-risk-pfqjadgl-en/landscape/romance-is-worth-the-risk-pfqjadgl-79b216088218e940657b51a4f6927114.jpeg?ts=1778071020&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 11 },
  { title: "Wife, Guard Your Spirit from Unfaithfulness", url: "https://www.desiringgod.org/articles/wife-guard-your-spirit-from-unfaithfulness", cover_image_url: "https://dg.imgix.net/wife-guard-your-spirit-from-unfaithfulness-77kc8e8h-en/landscape/wife-guard-your-spirit-from-unfaithfulness-77kc8e8h-be6f2adc00b611fd384848c4f74f1666.jpeg?ts=1774629951&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 12 },
  { title: "Don’t Mistake Dating for Marriage", url: "https://www.desiringgod.org/articles/dont-mistake-dating-for-marriage", cover_image_url: "https://dg.imgix.net/don-t-mistake-dating-for-marriage-vpzqtjyf-en/landscape/don-t-mistake-dating-for-marriage-vpzqtjyf-4400dec76a8a57c226e7400084898c6c.jpeg?ts=1774363119&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 13 },
  { title: "Ten Ways to Pray for Your Wife", url: "https://www.desiringgod.org/articles/ten-ways-to-pray-for-your-wife", cover_image_url: "https://dg.imgix.net/ten-ways-to-pray-for-your-wife-qeojwyzq-en/landscape/ten-ways-to-pray-for-your-wife-qeojwyzq.jpg?ts=1482954323&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 14 },
  { title: "Wives Speak Out", url: "https://www.thegospelcoalition.org/article/wives-speak-out/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2011/11/27122705/micheile-henderson-gnm2op0m2pw-unsplash.jpg", source: "The Gospel Coalition", growth_paths: ["LR"], sequence_order: 15 },
  { title: "Promote Marriage and Dignify Singleness by Prioritizing God’s Mission", url: "https://www.thegospelcoalition.org/article/marriage-singleness-mission/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2024/01/03093815/marriage-singleness-mission.jpg", source: "The Gospel Coalition", growth_paths: ["LR", "PP"], sequence_order: 16 },
  { title: "Help Your Wife Thrive Through Motherhood", url: "https://www.desiringgod.org/articles/help-your-wife-thrive-through-motherhood", cover_image_url: "https://dg.imgix.net/help-your-wife-thrive-through-motherhood-qyzvtstb-en/landscape/help-your-wife-thrive-through-motherhood-qyzvtstb-fa051740df243ec367b1bcecdd973dec.jpeg?ts=1778866912&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 17 },
  { title: "Motherhood Is a Refining Fire", url: "https://www.desiringgod.org/articles/motherhood-is-a-refining-fire", cover_image_url: "https://dg.imgix.net/motherhood-is-a-refining-fire-6ylvx58u-en/landscape/motherhood-is-a-refining-fire-6ylvx58u-a76ea514fa1499d132bc38af095f6f31.jpeg?ts=1763576398&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 18 },
  { title: "The Sacred Life of a Mother’s Mind", url: "https://www.desiringgod.org/articles/the-sacred-life-of-a-mothers-mind", cover_image_url: "https://dg.imgix.net/the-sacred-life-of-a-mother-s-mind-h7fykdhe-en/landscape/the-sacred-life-of-a-mother-s-mind-h7fykdhe-68e48cc481b0f884ca9517f26345d680.jpg?ts=1647371256&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 19 },
  { title: "The Power of a Praying Mother", url: "https://www.desiringgod.org/articles/the-power-of-a-praying-mother", cover_image_url: "https://dg.imgix.net/the-power-of-a-praying-mother-s87xbbc8-en/landscape/the-power-of-a-praying-mother-s87xbbc8-f988432db8a651aa2728a86cb451f987.jpg?ts=1643740943&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["LR"], sequence_order: 20 },
  { title: "What Motherhood Teaches Us about Womanhood", url: "https://www.crossway.org/articles/what-motherhood-teaches-us-about-womanhood/", cover_image_url: "https://static.crossway.org/articles/images/women-in-church-excerpt01.jpg", source: "Crossway", growth_paths: ["LR"], sequence_order: 21 },
  { title: "God’s Grand Plan for Motherhood", url: "https://www.crossway.org/articles/gods-grand-plan-for-motherhood/", cover_image_url: "https://static.crossway.org/articles/images/blog-image10.jpg", source: "Crossway", growth_paths: ["LR"], sequence_order: 22 },
  { title: "The Remedy for Our Helicopter Parenting", url: "https://www.thegospelcoalition.org/article/the-remedy-for-our-helicopter-parenting/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2017/06/15225838/the-remedy-for-our-helicopter-parenting.jpg", source: "The Gospel Coalition", growth_paths: ["LR"], sequence_order: 23 },
  { title: "When Motherhood Feels Invisible", url: "https://www.thegospelcoalition.org/article/motherhood-feels-invisible/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2024/08/15180122/motherhood-feels-invisible.jpg", source: "The Gospel Coalition", growth_paths: ["LR"], sequence_order: 24 },
  { title: "When Motherhood Isn’t Enough", url: "https://www.thegospelcoalition.org/article/motherhood-isnt-enough/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2019/11/13161215/lightstock_456426_medium_tgc.jpg", source: "The Gospel Coalition", growth_paths: ["LR"], sequence_order: 25 },

  // ─── Personal Growth (PG) ────────────────────────────────────────────
  { title: "Before You Rule, Rule Yourself", url: "https://www.desiringgod.org/articles/before-you-rule-rule-yourself", cover_image_url: "https://dg.imgix.net/before-you-rule-rule-yourself-pzcsxdlm-en/landscape/before-you-rule-rule-yourself-pzcsxdlm-d697269111beee4eaaa537a687e5314c.jpeg?ts=1765819361&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 26 },
  { title: "The Quiet Strength of Godly Fear", url: "https://www.desiringgod.org/articles/the-quiet-strength-of-godly-fear", cover_image_url: "https://dg.imgix.net/the-quiet-strength-of-godly-fear-bhdrip7e-en/landscape/the-quiet-strength-of-godly-fear-bhdrip7e-2e816b30d24ffcb478437ea2de5bcc44.jpg?ts=1733189316&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 27 },
  { title: "A Woman’s Strength Can Grow", url: "https://www.desiringgod.org/articles/a-womans-strength-can-grow", cover_image_url: "https://dg.imgix.net/a-woman-s-strength-can-grow-iqy76joi-en/landscape/a-woman-s-strength-can-grow-iqy76joi-c41e90e2c3a0fd7bcf183c1a8ebbe391.jpeg?ts=1758820562&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 28 },
  { title: "More Wonderful Than Being Beautiful", url: "https://www.desiringgod.org/articles/more-wonderful-than-being-beautiful", cover_image_url: "https://dg.imgix.net/more-wonderful-than-being-beautiful-eoq43jmr-en/landscape/more-wonderful-than-being-beautiful-eoq43jmr-d1d624b9ce29bf032afb82660c1966be.jpg?ts=1717191959&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 29 },
  { title: "Following Christ in a Female Body", url: "https://www.desiringgod.org/articles/following-christ-in-a-female-body", cover_image_url: "https://dg.imgix.net/following-christ-in-a-female-body-iephki1a-en/landscape/following-christ-in-a-female-body-iephki1a-27334ef8b2e5d5847755c1e85f83e547.jpg?ts=1686155085&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 30 },
  { title: "Lay Aside the Weight of Irritability", url: "https://www.desiringgod.org/articles/lay-aside-the-weight-of-irritability", cover_image_url: "https://dg.imgix.net/lay-aside-the-weight-of-irritability-ysl13x5i-en/landscape/lay-aside-the-weight-of-irritability-ysl13x5i.jpg?ts=1500478739&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 31 },
  { title: "How Healthy Is Your Soul? Six Questions for a New Year", url: "https://www.desiringgod.org/articles/how-healthy-is-your-soul", cover_image_url: "https://dg.imgix.net/how-healthy-is-your-soul-gp5l2jxt-en/landscape/how-healthy-is-your-soul-gp5l2jxt-39297b0a1cb09603f9f49c19d647b503.jpg?ts=1734028785&ixlib=rails-4.3.1&fit=crop&w=2000&h=1050", source: "Desiring God", growth_paths: ["PG"], sequence_order: 32 },
  { title: "Your Womanhood Is Not on Hold", url: "https://www.thegospelcoalition.org/article/your-womanhood-is-not-on-hold/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2013/02/02212330/edward-cisneros-415590-unsplash.jpg", source: "The Gospel Coalition", growth_paths: ["PG", "PP"], sequence_order: 33 },
  { title: "What Women Need to Know About Being Image-Bearers of God", url: "https://www.thegospelcoalition.org/article/what-women-need-to-know-about-being-image-bearers-of-god/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2017/10/25173824/women-child-of-god-2.jpg", source: "The Gospel Coalition", growth_paths: ["PG", "PP"], sequence_order: 34 },

  // ─── Purpose & Progress (PP) ─────────────────────────────────────────
  { title: "Women, Callings, and Having It All", url: "https://www.thegospelcoalition.org/article/women-callings-and-having-it-all/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2012/06/16202200/edward-cisneros-415590-unsplash.jpg", source: "The Gospel Coalition", growth_paths: ["PP"], sequence_order: 35 },
  { title: "The Call and Challenge of Women’s Work", url: "https://www.thegospelcoalition.org/article/call-challenge-womens-work/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2022/02/03195448/womens-work.jpg", source: "The Gospel Coalition", growth_paths: ["PP"], sequence_order: 36 },
  { title: "Womanhood: Embrace Your God-Given Identity and Purpose", url: "https://africa.thegospelcoalition.org/article/womanhood-embrace-your-god-given-identity-and-purpose/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/sites/7/2022/03/02150636/women.jpg", source: "The Gospel Coalition Africa", growth_paths: ["PP"], sequence_order: 37 },
  { title: "Singleness with Purpose", url: "https://www.thegospelcoalition.org/article/singleness-with-purpose/", cover_image_url: "https://media.thegospelcoalition.org/wp-content/uploads/2010/11/24150058/saeed-mhmdi-azbZUNpu1Ag-unsplash.jpg", source: "The Gospel Coalition", growth_paths: ["PP"], sequence_order: 38 },
];
